const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token, // 用户token
  avatar: state => state.user.avatar,
  name: state => state.user.name, // 用户name
  id: state => state.user.id, // 用户id
  info_num: state => state.user.info_num, // 用户未读消息数
  error_num: state => state.user.error_num, // 用户未读故障消息数
  auth_info: state => state.user.auth_info, // 用户消息状态
  error_info: state => state.user.error_info, // 用户故障消息状态
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles, // 用户访问权限
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs,
  isw: state => state.mflow.isw,
  curJzId: state => state.mflow.curJzId, // 数据流程当前设备id
  curJzId2: state => state.mflow.curJzId2, // 实时流程当前设备id
  curProId: state => state.mflow.curProId, // 数据流程当前选择的项目
  curProId2: state => state.mflow.curProId2, // 实时流程当前选择的项目
  upWhich: state => state.mflow.upWhich, // 流程中节点移动时要调用方法
  dflowMsg: state => state.mflow.dflowMsg, // 数据流程每次运行返回数据数组
  curDroveIndex: state => state.mflow.curDroveIndex, // 当前选择的数据流程设备（文件或设备）索引
  curNodeDataItemEnum: state => state.mflow.curNodeDataItemEnum,
  opreates: state => state.mflow.opreates,
  planid: state => state.etl.planid, // 预处理当前使用方案
  dfws: state => state.ws.dfws, // 数据流程websocket对象
  rfws: state => state.ws.rfws, // 实时流程websocket对象
  rfwsdata: state => state.ws.rfwsdata, // 实时流程返回的数据
  notifyws: state => state.ws.notifyws, // 系统消息websocket
  errorws: state => state.ws.errorws, // 故障消息websocket
  btndata: state => state.permission.btnData,
  metadataId: state => state.metadata.metadataId
}
export default getters
